In [1]:
import numpy as np
import pandas as pd

In [22]:
left = pd.DataFrame({'key1': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],                    
                     'B': ['B0', 'B1', 'B2', 'B3']})
left

key1   A   B
0   K0  A0  B0
1   K1  A1  B1
2   K2  A2  B2
3   K3  A3  B3

In [18]:
right = pd.DataFrame({'key2': ['K0', 'K1', 'K2'],
                       'C': ['C0', 'C1', 'C2'],
                         'D': ['D0', 'D1', 'D2']})
right

key2   C   D
0   K0  C0  D0
1   K1  C1  D1
2   K2  C2  D2

In [20]:
result = pd.merge(left, right, left_on='key1',right_on='key2',how='left',suffixes=('_x','_y'))

In [26]:
list1 = result['key1']

In [33]:
a = [1,2,3,34]
b = [4,5,656]

In [34]:
xx,yy = np.meshgrid(a,b)

In [35]:
xx

array([[ 1,  2,  3, 34],
       [ 1,  2,  3, 34],
       [ 1,  2,  3, 34]])

In [36]:
yy

array([[  4,   4,   4,   4],
       [  5,   5,   5,   5],
       [656, 656, 656, 656]])

In [45]:
xx.ravel()
yy.ravel()
[xx.ravel(),yy.ravel()]

xx.ravel().shape

(12,)

In [42]:
np.c_[xx.ravel(),yy.ravel()]

array([[  1,   4],
       [  2,   4],
       [  3,   4],
       [ 34,   4],
       [  1,   5],
       [  2,   5],
       [  3,   5],
       [ 34,   5],
       [  1, 656],
       [  2, 656],
       [  3, 656],
       [ 34, 656]])

In [44]:
range(2)

range(0, 2)

In [55]:
'this is a test for text format %s' % 'madongs'

'this is a test for text format madongs'

In [56]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
   ...:                           'foo', 'bar', 'foo', 'foo'],
   ...:                    'B' : ['one', 'one', 'two', 'three',
   ...:                           'two', 'two', 'one', 'three'],
   ...:                    'C' : np.random.randn(8),
   ...:                    'D' : np.random.randn(8)})
   ...: 


In [57]:
df

A      B         C         D
0  foo    one -1.145485 -1.404833
1  bar    one  0.668148 -0.228469
2  foo    two  1.662093 -0.395726
3  bar  three -1.195800 -1.329239
4  foo    two -1.093029 -3.220682
5  bar    two -1.451385 -0.010470
6  foo    one -0.932404 -0.336586
7  foo  three -1.085655  0.726976

In [112]:
grouped = df.groupby(['A','B'])['C']

In [113]:
grouped.apply(lambda x:x)

0   -1.145485
1    0.668148
2    1.662093
3   -1.195800
4   -1.093029
5   -1.451385
6   -0.932404
7   -1.085655
Name: C, dtype: float64

In [114]:
def f(group):
    print(group.get_values())
    print(group.name)
    return pd.DataFrame({'original' : group,
                           'demeaned' : group - group.mean()})

In [115]:
grouped.apply(f)

[0.66814842]
('bar', 'one')
[-1.19580042]
('bar', 'three')
[-1.45138495]
('bar', 'two')
[-1.14548461 -0.93240428]
('foo', 'one')
[-1.08565499]
('foo', 'three')
[ 1.66209282 -1.09302872]
('foo', 'two')


original  demeaned
0 -1.145485 -0.106540
1  0.668148  0.000000
2  1.662093  1.377561
3 -1.195800  0.000000
4 -1.093029 -1.377561
5 -1.451385  0.000000
6 -0.932404  0.106540
7 -1.085655  0.000000

## Groupby pol_no and alpha_id to got benefit type of rider

In [286]:
benefitData = pd.read_csv('./benefit.csv')
uwData = pd.read_csv('./uw_decision.csv')

In [287]:
benefitDataCopy = benefitData.copy()
uwDataCopy = uwData.copy()

In [288]:
benefitDataCopy
uwDataCopy

pol_no  alpha_id  rider   short_Name  phase_code
0  M0929       992      0  madongdong1        2333
1  M0929       992      1  madongdong2        2334
2  M0929       992      1  madongdong3        2335
3  M0929       992      1  madongdong4        2336

In [289]:
uw = uwDataCopy.groupby(['pol_no','alpha_id','rider'])['short_Name','phase_code']

In [290]:
groups = uw.groups

In [292]:
class genetateRider():
    def __init__(self,num):
        self.rider = 'rider' + str(num)
        self.phasecode = self.rider + '_phasecode'
        self.decision = self.rider  + '_decision'
        self.benefit = self.rider + '_benefit'
        
        
    

In [293]:
genetateRider(1).benefit

'rider1_benefit'

In [294]:
riderList = ['rider1_benefit','rider1_decision','rider1_phasecode',
            'rider2_benefit','rider2_decision','rider2_phasecode',
            'rider3_benefit','rider3_decision','rider3_phasecode',
            'rider4_benefit','rider4_decision','rider4_phasecode',
            'rider5_benefit','rider5_decision','rider5_phasecode',
            'rider6_benefit','rider6_decision','rider6_phasecode',
            'rider7_benefit','rider7_decision','rider7_phasecode',
            'rider8_benefit','rider8_decision','rider8_phasecode',
            'rider9_benefit','rider9_decision','rider9_phasecode']
tempSeries = pd.Series(index=riderList)
formatedData = pd.DataFrame(columns=riderList)
tempSeries['rider1_benefit'] = 1
tempSeries

rider1_benefit      1.0
rider1_decision     NaN
rider1_phasecode    NaN
rider2_benefit      NaN
rider2_decision     NaN
rider2_phasecode    NaN
rider3_benefit      NaN
rider3_decision     NaN
rider3_phasecode    NaN
rider4_benefit      NaN
rider4_decision     NaN
rider4_phasecode    NaN
rider5_benefit      NaN
rider5_decision     NaN
rider5_phasecode    NaN
rider6_benefit      NaN
rider6_decision     NaN
rider6_phasecode    NaN
rider7_benefit      NaN
rider7_decision     NaN
rider7_phasecode    NaN
rider8_benefit      NaN
rider8_decision     NaN
rider8_phasecode    NaN
rider9_benefit      NaN
rider9_decision     NaN
rider9_phasecode    NaN
dtype: float64

In [298]:
for g in groups:
    
    print('==========================='+str(g)+'==============')
    
    benefits = uw.get_group(g)
  #  print(benefits['phase_code'])
    phases = benefits['phase_code']
  #  print(phases)
    num = 1
    tempSeries = pd.Series(index=riderList)

    for phase in phases:
        print('------'+str(phase)+'------')
        print('-----count----'+str(num)+'-----')
        benefit = benefitDataCopy[benefitDataCopy['phase_code'] == phase][['benifit_life','benefit_sg','benefit_cancel']].reset_index()
        print(benefit)
        tempSeries[genetateRider(num).benefit] = benefit['benifit_life'][0]
        tempSeries[genetateRider(num).phasecode] = benefit['benefit_sg'][0]
        tempSeries[genetateRider(num).decision] = benefit['benefit_cancel'][0]
        num += 1
    tempSeries.name = g
    
    formatedData = formatedData.append(tempSeries)

===========================('M0929', 992, 0)==============
------2333------
-----count----1-----
   index benifit_life benefit_sg benefit_cancel
0      0            Y        NaN            NaN
===========================('M0929', 992, 1)==============
------2334------
-----count----1-----
   index benifit_life benefit_sg benefit_cancel
0      1            Y          Y              Y
1      5          NaN          Y              Y
------2335------
-----count----2-----
   index benifit_life benefit_sg benefit_cancel
0      2            Y        NaN            NaN
------2336------
-----count----3-----
   index benifit_life benefit_sg benefit_cancel
0      3          NaN          Y            NaN
1      4          NaN          Y            NaN


In [299]:
tempSeries

rider1_benefit        Y
rider1_decision       Y
rider1_phasecode      Y
rider2_benefit        Y
rider2_decision     NaN
rider2_phasecode    NaN
rider3_benefit      NaN
rider3_decision     NaN
rider3_phasecode      Y
rider4_benefit      NaN
rider4_decision     NaN
rider4_phasecode    NaN
rider5_benefit      NaN
rider5_decision     NaN
rider5_phasecode    NaN
rider6_benefit      NaN
rider6_decision     NaN
rider6_phasecode    NaN
rider7_benefit      NaN
rider7_decision     NaN
rider7_phasecode    NaN
rider8_benefit      NaN
rider8_decision     NaN
rider8_phasecode    NaN
rider9_benefit      NaN
rider9_decision     NaN
rider9_phasecode    NaN
Name: (M0929, 992, 1), dtype: object

In [300]:
formatedData

rider1_benefit rider1_decision rider1_phasecode  \
(M0929, 992, 0)              Y             NaN              NaN   
(M0929, 992, 1)              Y               Y                Y   

                rider2_benefit rider2_decision rider2_phasecode  \
(M0929, 992, 0)            NaN             NaN              NaN   
(M0929, 992, 1)              Y             NaN              NaN   

                rider3_benefit rider3_decision rider3_phasecode  \
(M0929, 992, 0)            NaN             NaN              NaN   
(M0929, 992, 1)            NaN             NaN                Y   

                rider4_benefit       ...        rider6_phasecode  \
(M0929, 992, 0)            NaN       ...                     NaN   
(M0929, 992, 1)            NaN       ...                     NaN   

                rider7_benefit rider7_decision rider7_phasecode  \
(M0929, 992, 0)            NaN             NaN              NaN   
(M0929, 992, 1)            NaN             NaN              NaN   

                rider8_benefit rider8_decision rider8_phasecode  \
(M0929, 992, 0)            NaN             NaN              NaN   
(M0929, 992, 1)            NaN             NaN              NaN   

                rider9_benefit rider9_decision rider9_phasecode  
(M0929, 992, 0)            NaN             NaN              NaN  
(M0929, 992, 1)            NaN             NaN              NaN  

[2 rows x 27 columns]

In [267]:
df = pd.DataFrame(np.random.randn(8, 4), columns=['A','B','C','D'])
df['A'][0]

-0.44141660328113397

In [235]:
s = df.xs(3)
s.name = 10

In [236]:
type(s)

pandas.core.series.Series

In [237]:
df.append(s)

A         B         C         D
0  -1.099692 -0.762857  0.948060  0.672159
1   0.357195  0.385001 -0.100577 -0.240805
2  -0.544789  1.010348 -0.884272 -0.335039
3   1.173761  1.847843 -1.510893 -0.849905
4  -0.916196  0.157785  1.716743  0.003005
5  -1.488514  0.378322 -1.051193  0.249220
6  -0.230268  0.470342  0.394191 -0.247089
7  -1.246809  0.168043  0.499522 -1.629160
10  1.173761  1.847843 -1.510893 -0.849905

In [1]:
import nltk

In [3]:
nltk.__version__

'3.3'

In [4]:
import wordcloud

In [5]:
wordcloud.__version__

'1.4.1'